### ISSUE TITLE
Invalid base64-encoded string

### ISSUE THREAD

**Issue by vitormnsousa** [microsoft/AIforEarthDataSets#23]
In advance fantastic work from all team.

I´m having an error when trying to reproduce the code at this point:

```
generator = container_client.list_blobs(name_starts_with=azure_scene_prefix)
scene_files = list(generator)
```
I try several products and get the same error. Can you please help me to solve this issue?

Thanks in advance.

Detailed error:

`---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/authentication.py in _add_authorization_header(self, request, string_to_sign)
    117         try:
--> 118             signature = sign_string(self.account_key, string_to_sign)
    119             auth_string = 'SharedKey ' + self.account_name + ':' + signature

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/__init__.py in sign_string(key, string_to_sign, key_is_base64)
     46     if key_is_base64:
---> 47         key = decode_base64_to_bytes(key)
     48     else:

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/__init__.py in decode_base64_to_bytes(data)
     36         data = data.encode('utf-8')
---> 37     return base64.b64decode(data)
     38 

/srv/conda/envs/notebook/lib/python3.8/base64.py in b64decode(s, altchars, validate)
     86         raise binascii.Error('Non-base64 digit found')
---> 87     return binascii.a2b_base64(s)
     88 

Error: Invalid base64-encoded string: number of data characters (37) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

AzureSigningError                         Traceback (most recent call last)
/tmp/ipykernel_359/1926042224.py in <module>
      1 generator = container_client.list_blobs(name_starts_with=azure_scene_prefix)
----> 2 scene_files = list(generator)
      3 image_blobs = [blob.name for blob in scene_files if blob.name.endswith('.tiff')]
      4 preview_blobs = [blob.name for blob in scene_files if blob.name.endswith('quick-look.png')]
      5 

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/paging.py in __next__(self)
    127         if self._page_iterator is None:
    128             self._page_iterator = itertools.chain.from_iterable(self.by_page())
--> 129         return next(self._page_iterator)
    130 
    131     next = __next__  # Python 2 compatibility.

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/paging.py in __next__(self)
     74             raise StopIteration("End of paging")
     75         try:
---> 76             self._response = self._get_next(self.continuation_token)
     77         except AzureError as error:
     78             if not error.continuation_token:

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_list_blobs_helper.py in _get_next_cb(self, continuation_token)
     77                 use_location=self.location_mode)
     78         except HttpResponseError as error:
---> 79             process_storage_error(error)
     80 
     81     def _extract_data_cb(self, get_next_return):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py in process_storage_error(storage_error)
     87     serialized = False
     88     if not storage_error.response:
---> 89         raise storage_error
     90     # If it is one of those three then it has been serialized prior by the generated layer.
     91     if isinstance(storage_error, (PartialBatchErrorException,

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_list_blobs_helper.py in _get_next_cb(self, continuation_token)
     70     def _get_next_cb(self, continuation_token):
     71         try:
---> 72             return self._command(
     73                 prefix=self.prefix,
     74                 marker=continuation_token or None,

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_container_operations.py in list_blob_flat_segment(self, prefix, marker, maxresults, include, timeout, request_id_parameter, **kwargs)
   1473 
   1474         request = self._client.get(url, query_parameters, header_parameters)
-> 1475         pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
   1476         response = pipeline_response.http_response
   1477 

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in run(self, request, **kwargs)
    209             else _TransportRunner(self._transport)
    210         )
--> 211         return first_node.send(pipeline_request)  # type: ignore

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py in send(self, request)
    156         redirect_settings = self.configure_redirects(request.context.options)
    157         while retryable:
--> 158             response = self.next.send(request)
    159             redirect_location = self.get_redirect_location(response)
    160             if redirect_location and redirect_settings['allow']:

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py in send(self, request)
    513                     self.sleep(retry_settings, request.context.transport)
    514                     continue
--> 515                 raise err
    516         if retry_settings['history']:
    517             response.context['history'] = retry_settings['history']

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py in send(self, request)
    487         while retries_remaining:
    488             try:
--> 489                 response = self.next.send(request)
    490                 if is_retry(response, retry_settings['mode']):
    491                     retries_remaining = self.increment(

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_base.py in send(self, request)
     67         :rtype: ~azure.core.pipeline.PipelineResponse
     68         """
---> 69         _await_result(self._policy.on_request, request)
     70         try:
     71             response = self.next.send(request)

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/core/pipeline/_tools.py in await_result(func, *args, **kwargs)
     27 def await_result(func, *args, **kwargs):
     28     """If func returns an awaitable, raise that this runner can't handle it."""
---> 29     result = func(*args, **kwargs)
     30     if hasattr(result, "__await__"):
     31         raise TypeError(

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/authentication.py in on_request(self, request)
    139             self._get_canonicalized_resource_query(request)
    140 
--> 141         self._add_authorization_header(request, string_to_sign)
    142         #logger.debug("String_to_sign=%s", string_to_sign)

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/authentication.py in _add_authorization_header(self, request, string_to_sign)
    122             # Wrap any error that occurred as signing error
    123             # Doing so will clarify/locate the source of problem
--> 124             raise _wrap_exception(ex, AzureSigningError)
    125 
    126     def on_request(self, request):

AzureSigningError: Invalid base64-encoded string: number of data characters (37) cannot be 1 more than a multiple of 4`

**Comment by TomAugspurger** [comment]
Hi @vitormnsousa. Can you share which notebook you're trying to reproduce, specifically the code you used to create the `container_client`?

**Comment by vitormnsousa** [comment]
Hi @TomAugspurger:

This is the notebook: https://nbviewer.org/github/microsoft/AIforEarthDataSets/blob/main/data/sentinel-1-grd.ipynb

The only thing that i change in this code was the username and password for Open Access Hub.

I can reproduce the code with the same results until "List matching blobs", that´s when i´m getting the error.

**Comment by TomAugspurger** [comment]
Thanks. Can you confirm that you have a SAS token at `~/tokens/sentinel1_ro_sas.txt`, and that the contents of that file starts with `?`?

**Comment by vitormnsousa** [comment]
Thanks. 
No i haven´t, i think since i was working in the Planetary Cmputer Hub it will no be necessary.
I have to get a SAS token from microsoft Azure? Can you send me documentation to do that?

**Comment by TomAugspurger** [comment]
See https://github.com/microsoft/AIforEarthDataSets/blob/main/data/sentinel-1-grd.md. If you could email ***@***.******@***.***?subject=sentinel1%20question>, we'll get you set up with a token.

Tom

**Comment by TomAugspurger** [comment]
Thanks for reaching out by email.
