### ISSUE TITLE
is # The doing of the doing a placeholder comment ??

### ISSUE THREAD

**Issue by smty2018** [microsoft/AIforEarthDataSets#46]
in https://github.com/microsoft/AIforEarthDataSets/blob/main/scripts/extract_storage_docs.py
is # The doing of the doing a placeholder comment ?? because it does not provide any proper interpretation of the code block below

![image](https://github.com/microsoft/AIforEarthDataSets/assets/74114936/6dc5425c-9d4c-4b46-8b7c-9a97a3f283eb)

**Comment by TomAugspurger** [comment]
I'm not sure.
