### ISSUE TITLE
Question: Data projection transform

### ISSUE THREAD

**Issue by gcoyle83** [microsoft/AIforEarthDataSets#48]
Hello,
I am getting familiar with the MSFT Planetary Computer datasets, specifically the [HRRR forecasts](https://planetarycomputer.microsoft.com/dataset/storage/noaa-hrrr). I have been reviewing the [example notebook](https://nbviewer.jupyter.org/github/microsoft/AIforEarthDataSets/blob/main/data/noaa-hrrr.ipynb) provided and I am confused by the projection transformations given. Specifically, I am confused by the need to provide the Plate Carree transform on the temperature plot, given that the dataset (ds.t) is in the Lambert Conformal projection, which is the same as the GeoAxes object for the plot. My understanding of the Cartopy library is that the transform parameter should indicate the data projection, and if it is left out, the GeoAxes projection is assumed to apply to the data, which should be the case for this example. However, if the Plate Carree transform is omitted, the data does not get mapped correctly (at all). I tried emailing the NOAA team with this question, but their email server rejected my message. Thanks for any information you can provide to help me understand this dataset better.

**Comment by TomAugspurger** [comment]
Thanks for reaching out. I'm not sure that we have any good reason for why those particular projection transformations are there.

**Comment by gcoyle83** [comment]
Okay, thanks anyway for your response. I'll go ahead and close this out, then.
